### ISSUE TITLE
every().then(()=>do something).until()

### ISSUE THREAD

**Issue by chrischjh** [akira-cn/wait-promise#1]
Nice beautiful wrapper :+1: 

Seems it doesn't support 

`every().then(()=>do something).until()`

would be nice to have it? Maybe not exactly be like that, just something to be more explicitly on "do something" instead of put it in `.until()`

**Comment by akira-cn** [comment]
That's cool.

It should be:

``` js
async function foo(){
  let i = 0, j = 0;
  await and(() => j++).until(() => j >= 3);
  await every(50).and(() => i++).until(()=> i >= 5);
  console.log(i + j); //will be 8
}
```

Thanks~

**Comment by chrischjh** [comment]
Neat!
Have updated my code, working perfectly.
Thanks!
